-- =====================================================================
-- 【廃止】このファイルは使用されません（no-op）。
--
-- DB スキーマは Spring Boot 起動時に Flyway が管理します。
-- スキーマの正: backend/src/main/resources/db/migration/V1__baseline_schema.sql
-- 以降の変更は V2__*.sql 以降を追加してください。
--
-- docker-compose.yml / docker-compose.prod.yml からの
-- docker-entrypoint-initdb.d マウントは撤去済みです。
-- （誤って読み込まれてもテーブルを作らないよう、中身は空にしています）
-- =====================================================================
